---

# Docker redirection breaks SSL auth chain
- name: Ensure common certificates are present
  apt: name={{item}} state=present update_cache=yes cache_valid_time={{cache_time}}
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add docker apt keys
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt: name=docker-engine state=present update_cache=yes

- name: Enable start on boot
  service: name=docker enabled=yes