---
- hosts: validator-api
  user: ubuntu
  become: yes
  roles:
    - docker_daemon
    - python
  tasks:
    - name: Install validator
      pip: name="git+https://github.com/ging/fiware-validator.git"

    - name: Run validator
      command: "validator_api"
