- name: Install pip, python-dev package with apt
  apt: name={{item}} state=latest update_cache=yes cache_valid_time={{cache_time}}
  with_items:
    - python-dev
    - python-pip
    - git
    - libffi-dev
    - libssl-dev
- name: Update pip SSL connections
  pip: name=pyopenssl